name: "Build and Test"
on:
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: install nix
      uses: cachix/install-nix-action@v6

    - name: build
      run: nix-build

    - name: test
      run: nix-shell --run check
