name: "Push to gh pages"
on:
  push:
    branches:
      - master
jobs:
  gen-doc-and-push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install nix
      uses: cachix/install-nix-action@v22

    - name: gen-doc
      run: nix develop --command ldoc .

    - name: push doc to gh pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./doc
